### ISSUE TITLE
Incorrect version of parallels

### ISSUE THREAD

**Issue by phareal** [trea/mac-m1-vagrant-parallels#1]
Hello 
i was trying to follow all the process in the Readme file but i have an error that say i need the last version of parallels but when i check i already have it 
`Build 'parallels-iso' errored after 18 seconds 853 milliseconds: Error starting VM: prlctl error: Failed to start the VM: To start "ubuntu-20.04-live-arm64", you need the latest version of Parallels Desktop. "ubuntu-20.04-live-arm64" was created in a newer version of Parallels Desktop and uses the features that are not supported in this one.`

**Comment by trea** [comment]
Parallels Desktop version 17.1.0 is the version I appear to have. Is yours the same? Did you also install the Virtualization SDK from https://www.parallels.com/products/desktop/download/#AdditionalDownloads?

**Comment by phareal** [comment]
Yes

Le mer. 17 nov. 2021 à 03:20, Trea Hauet ***@***.***> a
écrit :

**Comment by trea** [comment]
I'm sorry but your best bet I think would be to reach out to Parallels support. Good luck!

**Comment by trea** [comment]
Hi @phareal, I was wondering if you were able to resolve this.  Was there anything I can add here to help?
